package eu.monniot.speed.ui.theme

import androidx.compose.ui.graphics.Color

// Green · Light palette (§2.1)
val GreenPrimary = Color(0xFF3b6939)
val GreenOnPrimary = Color(0xFFffffff)
val GreenPrimaryContainer = Color(0xFFbcf0b4)
val GreenOnPrimaryContainer = Color(0xFF002106)
val GreenSecondary = Color(0xFF52634f)
val GreenSecondaryContainer = Color(0xFFd5e8cf)
val GreenOnSecondaryContainer = Color(0xFF101f10)
val GreenTertiary = Color(0xFF38656a)
val GreenTertiaryContainer = Color(0xFFbcebf0)
val GreenOnTertiaryContainer = Color(0xFF002023)
val GreenError = Color(0xFFba1a1a)
val GreenErrorContainer = Color(0xFFffdad6)
val GreenOnErrorContainer = Color(0xFF410002)
val GreenSurface = Color(0xFFf7fbf1)
val GreenSurfaceDim = Color(0xFFd7dbd2)
val GreenSurfaceContainerLow = Color(0xFFf1f5eb)
val GreenSurfaceContainer = Color(0xFFebefe5)
val GreenSurfaceContainerHigh = Color(0xFFe5e9df)
val GreenSurfaceContainerHighest = Color(0xFFe0e4da)
val GreenOnSurface = Color(0xFF181d17)
val GreenOnSurfaceVariant = Color(0xFF424940)
val GreenOutline = Color(0xFF72796f)
val GreenOutlineVariant = Color(0xFFc1c9bd)

// Green · Dark palette (§2.1)
val GreenDarkPrimary = Color(0xFFa1d39a)
val GreenDarkOnPrimary = Color(0xFF0a390f)
val GreenDarkPrimaryContainer = Color(0xFF235024)
val GreenDarkOnPrimaryContainer = Color(0xFFbcf0b4)
val GreenDarkSecondary = Color(0xFFb9ccb4)
val GreenDarkSecondaryContainer = Color(0xFF3a4b38)
val GreenDarkOnSecondaryContainer = Color(0xFFd5e8cf)
val GreenDarkTertiary = Color(0xFFa0cfd4)
val GreenDarkTertiaryContainer = Color(0xFF1e4d52)
val GreenDarkOnTertiaryContainer = Color(0xFFbcebf0)
val GreenDarkError = Color(0xFFffb4ab)
val GreenDarkErrorContainer = Color(0xFF93000a)
val GreenDarkOnErrorContainer = Color(0xFFffdad6)
val GreenDarkSurface = Color(0xFF10140f)
val GreenDarkSurfaceContainerLow = Color(0xFF181d17)
val GreenDarkSurfaceContainer = Color(0xFF1c211b)
val GreenDarkSurfaceContainerHigh = Color(0xFF272b25)
val GreenDarkSurfaceContainerHighest = Color(0xFF313630)
val GreenDarkOnSurface = Color(0xFFe0e4da)
val GreenDarkOnSurfaceVariant = Color(0xFFc1c9bd)
val GreenDarkOutline = Color(0xFF8b9286)
val GreenDarkOutlineVariant = Color(0xFF424940)
